{
 "title": "Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Issues By Type",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT issue_type AS \"Issue Type\", COUNT (issue_type) AS \"Count\" FROM issues GROUP BY issue_type ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Issues By Resolution",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT issue_resolution AS \"Issue Resolution\", COUNT (issue_resolution) AS \"Count\" FROM issues GROUP BY issue_resolution ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Issues By Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT issue_status AS \"Issue Status\", COUNT (issue_status) AS \"Count\" FROM issues GROUP BY issue_status ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Issues By Priority",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT issue_priority AS \"Issue Priority\", COUNT (issue_priority) AS \"Count\" FROM issues GROUP BY issue_priority ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Issues By Estimate",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT issue_story_points AS \"Estimate\", COUNT (issue_story_points) AS \"Count\" FROM issues GROUP BY issue_story_points ORDER BY 1;"
    }
   ]
  }
 ]
}